export const DomainErrorCode = {
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  PREREQUISITE_NOT_MET: "PREREQUISITE_NOT_MET",
  NETWORK_INCOMPATIBLE: "NETWORK_INCOMPATIBLE",
  NETWORK_INACTIVE: "NETWORK_INACTIVE",
  MAX_DIRECT_CELLS_REACHED: "MAX_DIRECT_CELLS_REACHED",
  CELL_NOT_FOUND: "CELL_NOT_FOUND",
  CELL_NOT_AUTHORIZED: "CELL_NOT_AUTHORIZED",
  CELL_NETWORK_INCOMPATIBLE: "CELL_NETWORK_INCOMPATIBLE",
  PERSON_NETWORK_INCOMPATIBLE: "PERSON_NETWORK_INCOMPATIBLE",
  MEMBERSHIP_ALREADY_ACTIVE: "MEMBERSHIP_ALREADY_ACTIVE",
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
  CELL_HAS_ACTIVE_MEMBERS: "CELL_HAS_ACTIVE_MEMBERS",
  ATTENDANCE_SESSION_ALREADY_EXISTS: "ATTENDANCE_SESSION_ALREADY_EXISTS",
  CELL_CONVERSION_PREREQUISITES_NOT_IMPLEMENTED:
    "CELL_CONVERSION_PREREQUISITES_NOT_IMPLEMENTED",
  CELL_CONVERSION_REQUIRES_MEMBER_RESOLUTION:
    "CELL_CONVERSION_REQUIRES_MEMBER_RESOLUTION",
  LEADER_NOT_ELIGIBLE: "LEADER_NOT_ELIGIBLE",
  LEADER_ALREADY_ACTIVE: "LEADER_ALREADY_ACTIVE",
  LEADER_REQUIRES_CELL: "LEADER_REQUIRES_CELL",
  LEADER_INVALID_ACTIVATOR: "LEADER_INVALID_ACTIVATOR",
  LEADER_DIFFERENT_MINISTRY: "LEADER_DIFFERENT_MINISTRY",
  LEADER_HAS_ACTIVE_STRUCTURE: "LEADER_HAS_ACTIVE_STRUCTURE",
  DIRECT_LEADER_REQUIRED: "DIRECT_LEADER_REQUIRED",
  DIRECT_LEADER_INVALID: "DIRECT_LEADER_INVALID",
  DIRECT_LEADER_CYCLE: "DIRECT_LEADER_CYCLE",
  DIRECT_LEADER_CAPACITY_REACHED: "DIRECT_LEADER_CAPACITY_REACHED",
  TWELVE_NOT_READY: "TWELVE_NOT_READY",
  TWELVE_REQUIRES_12_ACTIVE_LEADERS: "TWELVE_REQUIRES_12_ACTIVE_LEADERS",
  TWELVE_MEMBER_NOT_ACTIVE_LEADER: "TWELVE_MEMBER_NOT_ACTIVE_LEADER",
  TWELVE_HAS_ORDINARY_MEMBERS: "TWELVE_HAS_ORDINARY_MEMBERS",
  TREE_ACCESS_DENIED: "TREE_ACCESS_DENIED",
  USERNAME_COLLISION: "USERNAME_COLLISION",
  CREDENTIAL_PROVISION_FAILED: "CREDENTIAL_PROVISION_FAILED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
} as const;

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode];

export class DomainError extends Error {
  readonly code: DomainErrorCode;
  readonly details?: Record<string, unknown>;

  constructor(
    code: DomainErrorCode,
    message: string,
    details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "DomainError";
    this.code = code;
    this.details = details;
  }
}

export function isDomainError(error: unknown): error is DomainError {
  return error instanceof DomainError;
}
