export const DomainErrorCode = {
  NOT_AUTHORIZED: "NOT_AUTHORIZED",
  PREREQUISITE_NOT_MET: "PREREQUISITE_NOT_MET",
  NETWORK_INCOMPATIBLE: "NETWORK_INCOMPATIBLE",
  NETWORK_INACTIVE: "NETWORK_INACTIVE",
  MAX_DIRECT_CELLS_REACHED: "MAX_DIRECT_CELLS_REACHED",
  CELL_NOT_FOUND: "CELL_NOT_FOUND",
  CELL_NOT_AUTHORIZED: "CELL_NOT_AUTHORIZED",
  CELL_NETWORK_INCOMPATIBLE: "CELL_NETWORK_INCOMPATIBLE",
  PERSON_NETWORK_INCOMPATIBLE: "PERSON_NETWORK_INCOMPATIBLE",
  MEMBERSHIP_ALREADY_ACTIVE: "MEMBERSHIP_ALREADY_ACTIVE",
  MEMBERSHIP_NOT_FOUND: "MEMBERSHIP_NOT_FOUND",
  CELL_HAS_ACTIVE_MEMBERS: "CELL_HAS_ACTIVE_MEMBERS",
  ATTENDANCE_SESSION_ALREADY_EXISTS: "ATTENDANCE_SESSION_ALREADY_EXISTS",
  CELL_CONVERSION_PREREQUISITES_NOT_IMPLEMENTED:
    "CELL_CONVERSION_PREREQUISITES_NOT_IMPLEMENTED",
  CELL_CONVERSION_REQUIRES_MEMBER_RESOLUTION:
    "CELL_CONVERSION_REQUIRES_MEMBER_RESOLUTION",
  LEADER_NOT_ELIGIBLE: "LEADER_NOT_ELIGIBLE",
  LEADER_ALREADY_ACTIVE: "LEADER_ALREADY_ACTIVE",
  LEADER_REQUIRES_CELL: "LEADER_REQUIRES_CELL",
  LEADER_INVALID_ACTIVATOR: "LEADER_INVALID_ACTIVATOR",
  LEADER_DIFFERENT_MINISTRY: "LEADER_DIFFERENT_MINISTRY",
  LEADER_HAS_ACTIVE_STRUCTURE: "LEADER_HAS_ACTIVE_STRUCTURE",
  DIRECT_LEADER_REQUIRED: "DIRECT_LEADER_REQUIRED",
  DIRECT_LEADER_INVALID: "DIRECT_LEADER_INVALID",
  DIRECT_LEADER_CYCLE: "DIRECT_LEADER_CYCLE",
  DIRECT_LEADER_CAPACITY_REACHED: "DIRECT_LEADER_CAPACITY_REACHED",
  TWELVE_NOT_READY: "TWELVE_NOT_READY",
  TWELVE_REQUIRES_12_ACTIVE_LEADERS: "TWELVE_REQUIRES_12_ACTIVE_LEADERS",
  TWELVE_MEMBER_NOT_ACTIVE_LEADER: "TWELVE_MEMBER_NOT_ACTIVE_LEADER",
  TWELVE_HAS_ORDINARY_MEMBERS: "TWELVE_HAS_ORDINARY_MEMBERS",
  TREE_ACCESS_DENIED: "TREE_ACCESS_DENIED",
  USERNAME_COLLISION: "USERNAME_COLLISION",
  CREDENTIAL_PROVISION_FAILED: "CREDENTIAL_PROVISION_FAILED",
  PROCESS_NOT_FOUND: "PROCESS_NOT_FOUND",
  PROCESS_ACCESS_DENIED: "PROCESS_ACCESS_DENIED",
  CONSOLIDATION_ALREADY_COMPLETED: "CONSOLIDATION_ALREADY_COMPLETED",
  CONSOLIDATION_REQUIRED: "CONSOLIDATION_REQUIRED",
  UDV_NOT_ELIGIBLE: "UDV_NOT_ELIGIBLE",
  UDV_ALREADY_ENROLLED: "UDV_ALREADY_ENROLLED",
  UDV_CYCLE_NOT_ACTIVE: "UDV_CYCLE_NOT_ACTIVE",
  UDV_ALREADY_COMPLETED: "UDV_ALREADY_COMPLETED",
  TRAINING_MODULE_INACTIVE: "TRAINING_MODULE_INACTIVE",
  ATTENDANCE_ALREADY_RECORDED: "ATTENDANCE_ALREADY_RECORDED",
  ATTENDANCE_RECOVERY_NOT_AUTHORIZED: "ATTENDANCE_RECOVERY_NOT_AUTHORIZED",
  CYCLE_ALREADY_ACTIVE: "CYCLE_ALREADY_ACTIVE",
  CYCLE_ALREADY_CLOSED: "CYCLE_ALREADY_CLOSED",
  CROSS_MINISTRY_PROCESS_DENIED: "CROSS_MINISTRY_PROCESS_DENIED",
  DESTINATION_LEVEL_1_NOT_ELIGIBLE: "DESTINATION_LEVEL_1_NOT_ELIGIBLE",
  DESTINATION_LEVEL_2_NOT_ELIGIBLE: "DESTINATION_LEVEL_2_NOT_ELIGIBLE",
  DESTINATION_LEVEL_3_NOT_ELIGIBLE: "DESTINATION_LEVEL_3_NOT_ELIGIBLE",
  DESTINATION_PREREQUISITE_NOT_MET: "DESTINATION_PREREQUISITE_NOT_MET",
  DESTINATION_ALREADY_COMPLETED: "DESTINATION_ALREADY_COMPLETED",
  DESTINATION_ALREADY_ENROLLED: "DESTINATION_ALREADY_ENROLLED",
  DESTINATION_CYCLE_NOT_ACTIVE: "DESTINATION_CYCLE_NOT_ACTIVE",
  DESTINATION_ACADEMIC_NOT_COMPLETED: "DESTINATION_ACADEMIC_NOT_COMPLETED",
  DESTINATION_PASTORAL_REQUIREMENT_NOT_MET: "DESTINATION_PASTORAL_REQUIREMENT_NOT_MET",
  DESTINATION_OVERRIDE_NOT_ALLOWED: "DESTINATION_OVERRIDE_NOT_ALLOWED",
  DESTINATION_INVALID_LEVEL: "DESTINATION_INVALID_LEVEL",
  DESTINATION_ACCESS_DENIED: "DESTINATION_ACCESS_DENIED",
  DESTINATION_CROSS_MINISTRY_DENIED: "DESTINATION_CROSS_MINISTRY_DENIED",
  MINISTERIAL_SCHOOL_NOT_ELIGIBLE: "MINISTERIAL_SCHOOL_NOT_ELIGIBLE",
  MINISTERIAL_SCHOOL_ALREADY_ENROLLED: "MINISTERIAL_SCHOOL_ALREADY_ENROLLED",
  MINISTERIAL_SCHOOL_CYCLE_NOT_ACTIVE: "MINISTERIAL_SCHOOL_CYCLE_NOT_ACTIVE",
  MINISTERIAL_SCHOOL_ACADEMIC_NOT_COMPLETED: "MINISTERIAL_SCHOOL_ACADEMIC_NOT_COMPLETED",
  MINISTERIAL_SCHOOL_REQUIREMENT_NOT_MET: "MINISTERIAL_SCHOOL_REQUIREMENT_NOT_MET",
  MINISTERIAL_SCHOOL_ALREADY_COMPLETED: "MINISTERIAL_SCHOOL_ALREADY_COMPLETED",
  MINISTERIAL_SCHOOL_ACCESS_DENIED: "MINISTERIAL_SCHOOL_ACCESS_DENIED",
  REENCOUNTER_NOT_ELIGIBLE: "REENCOUNTER_NOT_ELIGIBLE",
  REENCOUNTER_ALREADY_ENROLLED: "REENCOUNTER_ALREADY_ENROLLED",
  REENCOUNTER_EVENT_NOT_ACTIVE: "REENCOUNTER_EVENT_NOT_ACTIVE",
  REENCOUNTER_ALREADY_COMPLETED: "REENCOUNTER_ALREADY_COMPLETED",
  REENCOUNTER_ACCESS_DENIED: "REENCOUNTER_ACCESS_DENIED",
  // Phase 8 — Enviar
  SEND_NOT_ELIGIBLE: "SEND_NOT_ELIGIBLE",
  SEND_ALREADY_COMPLETED: "SEND_ALREADY_COMPLETED",
  SEND_ACCESS_DENIED: "SEND_ACCESS_DENIED",
  // Phase 8 — Transfers / reassignment
  TRANSFER_NOT_FOUND: "TRANSFER_NOT_FOUND",
  TRANSFER_ALREADY_EXECUTED: "TRANSFER_ALREADY_EXECUTED",
  TRANSFER_NOT_APPROVED: "TRANSFER_NOT_APPROVED",
  TRANSFER_INVALID_ACTOR: "TRANSFER_INVALID_ACTOR",
  TRANSFER_INVALID_DESTINATION: "TRANSFER_INVALID_DESTINATION",
  TRANSFER_CROSS_MINISTRY_APPROVAL_REQUIRED: "TRANSFER_CROSS_MINISTRY_APPROVAL_REQUIRED",
  TRANSFER_NETWORK_INCOMPATIBLE: "TRANSFER_NETWORK_INCOMPATIBLE",
  REASSIGNMENT_PLAN_REQUIRED: "REASSIGNMENT_PLAN_REQUIRED",
  REASSIGNMENT_INCOMPLETE: "REASSIGNMENT_INCOMPLETE",
  REASSIGNMENT_WOULD_ORPHAN_PERSON: "REASSIGNMENT_WOULD_ORPHAN_PERSON",
  LEADER_SUBTREE_MOVE_INVALID: "LEADER_SUBTREE_MOVE_INVALID",
  LEADER_SUBTREE_CYCLE: "LEADER_SUBTREE_CYCLE",
  LEADER_PARENT_CAPACITY_REACHED: "LEADER_PARENT_CAPACITY_REACHED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
} as const;

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode];

export class DomainError extends Error {
  readonly code: DomainErrorCode;
  readonly details?: Record<string, unknown>;

  constructor(
    code: DomainErrorCode,
    message: string,
    details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "DomainError";
    this.code = code;
    this.details = details;
  }
}

export function isDomainError(error: unknown): error is DomainError {
  return error instanceof DomainError;
}
