import type { ExecutiveDashboard } from "@/modules/reporting/dashboard";

/** Fixture for /ui-preview — visual only; not production metrics. */
export const previewDashboard: ExecutiveDashboard = {
  scope: {
    mode: "ministry",
    roleView: "leader_general",
    ministryIds: ["prev-ministry"],
    networkId: null,
    rootPersonId: "prev-root",
  },
  period: {
    key: "this_month",
    label: "Este mes",
    from: new Date("2026-08-01T05:00:00.000Z"),
    to: new Date("2026-08-16T05:00:00.000Z"),
    prevFrom: new Date("2026-07-01T05:00:00.000Z"),
    prevTo: new Date("2026-07-31T05:00:00.000Z"),
  },
  persons: {
    methodology: "current_state",
    totalActive: 248,
    withCell: 180,
    withoutCell: 68,
    newInPeriod: 22,
    newPreviousPeriod: 18,
    newChangeLabel: "+22%",
    bySource: { public_form: 14, internal_form: 8 },
    prayerPendingCount: 3,
    byNetwork: [],
    byMinistry: [],
  },
  ladder: {
    methodology: "current_state_counts",
    note: "Conteos actuales por etapa; no son tasas de conversión de cohorte histórica.",
    ganarCompleted: 248,
    consolidar: {
      pre: {
        eligible: 4,
        in_progress: 18,
        academic_completed: 0,
        completed: 42,
        paused: 1,
        pending: 0,
        total: 65,
      },
      encuentro: {
        eligible: 2,
        in_progress: 12,
        academic_completed: 0,
        completed: 36,
        paused: 0,
        pending: 0,
        total: 50,
      },
      post: {
        eligible: 3,
        in_progress: 9,
        academic_completed: 0,
        completed: 28,
        paused: 0,
        pending: 0,
        total: 40,
      },
      consolidarCompleted: 28,
    },
    discipular: {
      cd1: {
        eligible: 2,
        in_progress: 10,
        academic_completed: 0,
        completed: 20,
        paused: 0,
        pending: 0,
        total: 32,
      },
      cd2: {
        eligible: 1,
        in_progress: 8,
        academic_completed: 0,
        completed: 14,
        paused: 0,
        pending: 0,
        total: 23,
      },
      reencuentro: {
        eligible: 2,
        in_progress: 6,
        academic_completed: 0,
        completed: 12,
        paused: 0,
        pending: 0,
        total: 20,
      },
      cd3: {
        eligible: 1,
        in_progress: 4,
        academic_completed: 0,
        completed: 8,
        paused: 0,
        pending: 0,
        total: 13,
      },
      em1: {
        eligible: 1,
        in_progress: 5,
        academic_completed: 0,
        completed: 7,
        paused: 0,
        pending: 0,
        total: 13,
      },
      em2: {
        eligible: 0,
        in_progress: 3,
        academic_completed: 0,
        completed: 5,
        paused: 0,
        pending: 0,
        total: 8,
      },
      em3: {
        eligible: 0,
        in_progress: 2,
        academic_completed: 0,
        completed: 4,
        paused: 0,
        pending: 0,
        total: 6,
      },
    },
    enviar: {
      eligible: 6,
      in_progress: 4,
      academic_completed: 0,
      completed: 18,
      paused: 0,
      pending: 0,
      total: 28,
      ungidos: 5,
      activados: 12,
    },
    funnel: [
      { code: "ganar", label: "GANAR", count: 248 },
      { code: "consolidar", label: "CONSOLIDAR", count: 65 },
      { code: "discipular", label: "DISCIPULAR", count: 98 },
      { code: "enviar", label: "ENVIAR", count: 28 },
    ],
  },
  leadership: {
    active: 36,
    eligible: 8,
    inactive: 2,
    activeWithCell: 33,
    activeWithoutCell: 3,
    activatedInPeriod: 2,
    twelveBuckets: { "0-3": 12, "4-7": 10, "8-11": 9, "12": 5 },
    generations: {
      depth1: 9,
      depth2: 21,
      depth3: 6,
      potentialLabel:
        "Reales depth1=9 (potencial 12), depth2=21 (potencial 144), depth3=6 (potencial 1728)",
    },
    focus: {
      personId: "prev-root",
      fullName: "Ana Pastor",
      code: "LG-01",
      progress: { current: 9, max: 12, ready: false, label: "9/12" },
      progressBand: "8-11",
    },
  },
  cells: {
    totalActive: 28,
    evangelistic: 20,
    twelve: 8,
    closed: 1,
    newInPeriod: 2,
    activeMembers: 176,
    avgAttendancePct: 78,
    noRecentAttendance: 2,
    attendanceDrop: 1,
  },
  transfers: {
    pending: 3,
    approved: 1,
    executedInPeriod: 2,
    rejectedInPeriod: 0,
    crossMinistryPending: 1,
  },
  alerts: [],
  attention: [
    {
      code: "active_leader_without_cell",
      severity: "critical",
      title: "Líder activo sin célula",
      detail: "Carlos Méndez",
      href: "/liderazgo/preview",
      entityType: "person_leadership",
      entityId: "p1",
    },
    {
      code: "cell_no_recent_attendance",
      severity: "warning",
      title: "Célula sin reporte reciente",
      detail: "Célula Norte · última 2026-08-01",
      href: "/celulas/preview",
      entityType: "cell",
      entityId: "c1",
    },
    {
      code: "pending_transfer",
      severity: "info",
      title: "Transferencia pendiente",
      detail: "person · pending",
      href: "/transferencias?estado=pending",
      entityType: "pastoral_transfer_requests",
      entityId: "t1",
    },
  ],
  tree: [
    {
      personId: "n1",
      fullName: "Lucia Ríos",
      code: "L-12",
      status: "active",
      networkId: null,
      directCount: 7,
      descendantCount: 19,
      cellCount: 1,
      readyForTwelve: false,
    },
    {
      personId: "n2",
      fullName: "Pedro Salas",
      code: "L-18",
      status: "active",
      networkId: null,
      directCount: 12,
      descendantCount: 34,
      cellCount: 1,
      readyForTwelve: true,
    },
  ],
  breadcrumbs: [
    { personId: "prev-root", fullName: "Ana Pastor", humanLeaderCode: "LG-01" },
  ],
  trends: {
    newPersonsWeekly: [
      { weekStart: "2026-06-23", count: 4 },
      { weekStart: "2026-06-30", count: 6 },
      { weekStart: "2026-07-07", count: 3 },
      { weekStart: "2026-07-14", count: 8 },
      { weekStart: "2026-07-21", count: 5 },
      { weekStart: "2026-07-28", count: 7 },
      { weekStart: "2026-08-04", count: 9 },
      { weekStart: "2026-08-11", count: 6 },
    ],
  },
  timings: { scope: 2, persons: 8, ladder: 11, leadership: 14, cells: 9, transfers: 3, alerts: 12, trends: 4 },
};

const emptyStage = {
  eligible: 0,
  in_progress: 0,
  academic_completed: 0,
  completed: 0,
  paused: 0,
  pending: 0,
  total: 0,
};

export const previewEmptyDashboard: ExecutiveDashboard = {
  ...previewDashboard,
  scope: {
    ...previewDashboard.scope,
    rootPersonId: null,
  },
  persons: {
    ...previewDashboard.persons,
    totalActive: 0,
    newInPeriod: 0,
    newPreviousPeriod: 0,
    newChangeLabel: "0%",
  },
  ladder: {
    methodology: "current_state_counts",
    note: previewDashboard.ladder.note,
    ganarCompleted: 0,
    consolidar: {
      pre: { ...emptyStage },
      encuentro: { ...emptyStage },
      post: { ...emptyStage },
      consolidarCompleted: 0,
    },
    discipular: {
      cd1: { ...emptyStage },
      cd2: { ...emptyStage },
      reencuentro: { ...emptyStage },
      cd3: { ...emptyStage },
      em1: { ...emptyStage },
      em2: { ...emptyStage },
      em3: { ...emptyStage },
    },
    enviar: { ...emptyStage, ungidos: 0, activados: 0 },
    funnel: [
      { code: "ganar", label: "GANAR", count: 0 },
      { code: "consolidar", label: "CONSOLIDAR", count: 0 },
      { code: "discipular", label: "DISCIPULAR", count: 0 },
      { code: "enviar", label: "ENVIAR", count: 0 },
    ],
  },
  leadership: {
    ...previewDashboard.leadership,
    active: 0,
    eligible: 0,
    activeWithCell: 0,
    activeWithoutCell: 0,
    generations: {
      depth1: 0,
      depth2: 0,
      depth3: 0,
      potentialLabel:
        "Reales depth1=0 (potencial 12), depth2=0 (potencial 144), depth3=0 (potencial 1728)",
    },
    focus: undefined,
  },
  cells: {
    ...previewDashboard.cells,
    totalActive: 0,
    evangelistic: 0,
    twelve: 0,
    activeMembers: 0,
    avgAttendancePct: null,
  },
  transfers: {
    pending: 0,
    approved: 0,
    executedInPeriod: 0,
    rejectedInPeriod: 0,
    crossMinistryPending: 0,
  },
  attention: [],
  tree: [],
  breadcrumbs: [],
  trends: { newPersonsWeekly: [] },
};
