/**
 * Provision ephemeral E2E users via Clerk + interim Postgres (`users.clerk_user_id`).
 * Refuses APP_ENV=production. Writes credentials to .env.e2e.local (gitignored).
 *
 * Requires:
 * - CLERK_SECRET_KEY
 * - DATABASE_URL pointing at non-Supabase Postgres (interim pastoral modules)
 *
 * Once pastoral data is fully on Convex, replace the Drizzle section with Convex mutations.
 *
 * Usage: npx tsx --env-file=.env.local scripts/provision-e2e-users.ts
 */
import { createHash, randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { eq } from "drizzle-orm";

import { getDb } from "@/db/client";
import {
  ministries,
  roles,
  userRoleAssignments,
  users,
} from "@/db/schema";
import { hasClerkSecret, hasDatabaseUrl } from "@/lib/env";

import { upsertClerkUserPassword } from "./lib/verify-env";

const APP_ENV = process.env.APP_ENV ?? "local";

const ACCOUNTS = [
  {
    key: "SUPERADMIN",
    email: "e2e.superadmin@multiplica.e2e.test",
    displayName: "E2E Superadmin",
    role: "superadmin",
    ministryScoped: false,
  },
  {
    key: "LEADER_GENERAL",
    email: "e2e.lg@multiplica.e2e.test",
    displayName: "E2E Líder General",
    role: "leader_general",
    ministryScoped: true,
  },
  {
    key: "LEADER",
    email: "e2e.leader@multiplica.e2e.test",
    displayName: "E2E Líder",
    role: "leader",
    ministryScoped: true,
  },
  {
    key: "STAFF",
    email: "e2e.staff@multiplica.e2e.test",
    displayName: "E2E Staff",
    role: "staff",
    ministryScoped: true,
  },
] as const;

function passwordFor(email: string) {
  const salt = process.env.E2E_PASSWORD_SALT ?? "multiplica-e2e-phase5";
  return createHash("sha256").update(`${salt}:${email}`).digest("hex").slice(0, 20) + "Aa1!";
}

async function main() {
  if (APP_ENV === "production") {
    console.error("Refusing to provision E2E users when APP_ENV=production");
    process.exit(1);
  }

  if (!hasClerkSecret()) {
    console.error(
      "Missing CLERK_SECRET_KEY. E2E provision requires Clerk Backend API.",
    );
    process.exit(1);
  }

  if (!hasDatabaseUrl()) {
    console.error(
      [
        "E2E provision requires interim non-Supabase DATABASE_URL to link",
        "users.clerk_user_id + roles (or a Convex-based provision path once cutover completes).",
        "Set DATABASE_URL to Neon/etc., or migrate pastoral users to Convex first.",
      ].join(" "),
    );
    process.exit(1);
  }

  const db = getDb();

  const [ministry] = await db
    .select()
    .from(ministries)
    .where(eq(ministries.code, "LP1"))
    .limit(1);
  if (!ministry) {
    console.error("Ministry LP1 required for scoped E2E users");
    process.exit(1);
  }

  const roleRows = await db.select().from(roles);
  const roleByCode = Object.fromEntries(roleRows.map((r) => [r.code, r]));

  const lines: string[] = [
    `# Generated by scripts/provision-e2e-users.ts — do not commit`,
    `E2E_MINISTRY_ID=${ministry.id}`,
  ];

  for (const account of ACCOUNTS) {
    const password = passwordFor(account.email);
    const role = roleByCode[account.role];
    if (!role) {
      console.error(`Missing role ${account.role}`);
      process.exit(1);
    }

    let clerkUserId: string;
    try {
      clerkUserId = await upsertClerkUserPassword(account.email, password, {
        mustChangePassword: false,
        e2e: true,
        role: account.role,
      });
    } catch (e) {
      console.error(account.email, e instanceof Error ? e.message : e);
      process.exit(1);
    }

    const [existing] = await db
      .select()
      .from(users)
      .where(eq(users.clerkUserId, clerkUserId))
      .limit(1);

    let appUserId: string;
    if (!existing) {
      const [byEmail] = await db
        .select()
        .from(users)
        .where(eq(users.email, account.email))
        .limit(1);
      if (byEmail) {
        await db
          .update(users)
          .set({
            clerkUserId,
            displayName: account.displayName,
            isActive: true,
            mustChangePassword: false,
            email: account.email,
          })
          .where(eq(users.id, byEmail.id));
        appUserId = byEmail.id;
      } else {
        const [inserted] = await db
          .insert(users)
          .values({
            clerkUserId,
            email: account.email,
            displayName: account.displayName,
            isActive: true,
            mustChangePassword: false,
            username: `e2e_${account.role}_${randomBytes(2).toString("hex")}`,
          })
          .returning({ id: users.id });
        appUserId = inserted.id;
      }
    } else {
      await db
        .update(users)
        .set({
          displayName: account.displayName,
          isActive: true,
          mustChangePassword: false,
          email: account.email,
        })
        .where(eq(users.id, existing.id));
      appUserId = existing.id;
    }

    const assignments = await db
      .select()
      .from(userRoleAssignments)
      .where(eq(userRoleAssignments.userId, appUserId));
    const active = assignments.find(
      (a) => a.roleId === role.id && (a.endsAt == null || a.endsAt > new Date()),
    );
    if (!active) {
      await db.insert(userRoleAssignments).values({
        userId: appUserId,
        roleId: role.id,
        ministryId: account.ministryScoped ? ministry.id : null,
      });
    }

    lines.push(`E2E_${account.key}_EMAIL=${account.email}`);
    lines.push(`E2E_${account.key}_PASSWORD=${password}`);
    lines.push(`E2E_${account.key}_USER_ID=${appUserId}`);
    lines.push(`E2E_${account.key}_CLERK_USER_ID=${clerkUserId}`);
    console.log(`OK ${account.role} ${account.email} app=${appUserId} clerk=${clerkUserId}`);
  }

  writeFileSync(".env.e2e.local", `${lines.join("\n")}\n`, "utf8");
  console.log("Wrote .env.e2e.local");
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
