/**
 * Provision ephemeral E2E users for Phase 5 pre-prod validation.
 * Refuses APP_ENV=production. Writes credentials to .env.e2e.local (gitignored).
 *
 * Usage: npx tsx --env-file=.env.local scripts/provision-e2e-users.ts
 */
import { createHash, randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { eq } from "drizzle-orm";

import { getDb } from "@/db/client";
import {
  ministries,
  roles,
  userRoleAssignments,
  users,
} from "@/db/schema";

const APP_ENV = process.env.APP_ENV ?? "local";

const ACCOUNTS = [
  {
    key: "SUPERADMIN",
    email: "e2e.superadmin@multiplica.e2e.test",
    displayName: "E2E Superadmin",
    role: "superadmin",
    ministryScoped: false,
  },
  {
    key: "LEADER_GENERAL",
    email: "e2e.lg@multiplica.e2e.test",
    displayName: "E2E Líder General",
    role: "leader_general",
    ministryScoped: true,
  },
  {
    key: "LEADER",
    email: "e2e.leader@multiplica.e2e.test",
    displayName: "E2E Líder",
    role: "leader",
    ministryScoped: true,
  },
  {
    key: "STAFF",
    email: "e2e.staff@multiplica.e2e.test",
    displayName: "E2E Staff",
    role: "staff",
    ministryScoped: true,
  },
] as const;

function passwordFor(email: string) {
  const salt = process.env.E2E_PASSWORD_SALT ?? "multiplica-e2e-phase5";
  return createHash("sha256").update(`${salt}:${email}`).digest("hex").slice(0, 20) + "Aa1!";
}

async function main() {
  if (APP_ENV === "production") {
    console.error("Refusing to provision E2E users when APP_ENV=production");
    process.exit(1);
  }

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    console.error("Missing Supabase env");
    process.exit(1);
  }

  const admin = createClient(url, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const db = getDb();

  const [ministry] = await db
    .select()
    .from(ministries)
    .where(eq(ministries.code, "LP1"))
    .limit(1);
  if (!ministry) {
    console.error("Ministry LP1 required for scoped E2E users");
    process.exit(1);
  }

  const roleRows = await db.select().from(roles);
  const roleByCode = Object.fromEntries(roleRows.map((r) => [r.code, r]));

  const lines: string[] = [
    `# Generated by scripts/provision-e2e-users.ts — do not commit`,
    `E2E_MINISTRY_ID=${ministry.id}`,
  ];

  for (const account of ACCOUNTS) {
    const password = passwordFor(account.email);
    const role = roleByCode[account.role];
    if (!role) {
      console.error(`Missing role ${account.role}`);
      process.exit(1);
    }

    const list = await admin.auth.admin.listUsers({ perPage: 200 });
    let userId = list.data.users.find((u) => u.email === account.email)?.id;

    if (!userId) {
      const created = await admin.auth.admin.createUser({
        email: account.email,
        password,
        email_confirm: true,
      });
      if (!created.data.user) {
        console.error(account.email, created.error?.message);
        process.exit(1);
      }
      userId = created.data.user.id;
    } else {
      await admin.auth.admin.updateUserById(userId, {
        password,
        email_confirm: true,
      });
    }

    const [existing] = await db
      .select()
      .from(users)
      .where(eq(users.id, userId))
      .limit(1);
    if (!existing) {
      await db.insert(users).values({
        id: userId,
        email: account.email,
        displayName: account.displayName,
        isActive: true,
        mustChangePassword: false,
        username: `e2e_${account.role}_${randomBytes(2).toString("hex")}`,
      });
    } else {
      await db
        .update(users)
        .set({
          displayName: account.displayName,
          isActive: true,
          mustChangePassword: false,
          email: account.email,
        })
        .where(eq(users.id, userId));
    }

    const assignments = await db
      .select()
      .from(userRoleAssignments)
      .where(eq(userRoleAssignments.userId, userId));
    const active = assignments.find(
      (a) => a.roleId === role.id && (a.endsAt == null || a.endsAt > new Date()),
    );
    if (!active) {
      await db.insert(userRoleAssignments).values({
        userId,
        roleId: role.id,
        ministryId: account.ministryScoped ? ministry.id : null,
      });
    }

    lines.push(`E2E_${account.key}_EMAIL=${account.email}`);
    lines.push(`E2E_${account.key}_PASSWORD=${password}`);
    lines.push(`E2E_${account.key}_USER_ID=${userId}`);
    console.log(`OK ${account.role} ${account.email}`);
  }

  writeFileSync(".env.e2e.local", `${lines.join("\n")}\n`, "utf8");
  console.log("Wrote .env.e2e.local");
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
