export const PERMISSION_SEEDS = [
  {
    code: "platform.configure",
    name: "Configurar plataforma",
    description: "Gestionar catálogos base y roles de sistema.",
  },
  {
    code: "ministry.manage",
    name: "Gestionar ministerios",
    description: "Crear/editar/activar Ministerios Generales (Superadmin).",
  },
  {
    code: "ministry.read",
    name: "Leer ministerios",
    description: "Ver Ministerios dentro del scope autorizado.",
  },
  {
    code: "network.read",
    name: "Leer redes",
    description: "Consultar catálogo de Redes.",
  },
  {
    code: "users.read",
    name: "Leer usuarios",
    description: "Listar usuarios de aplicación dentro del scope.",
  },
  {
    code: "users.assign_roles",
    name: "Asignar roles",
    description: "Asignar roles y responsable de Ministerio.",
  },
  {
    code: "persons.read",
    name: "Leer personas",
    description: "Ver personas dentro del scope autorizado.",
  },
  {
    code: "persons.write",
    name: "Escribir personas",
    description: "Crear/actualizar personas dentro del scope autorizado.",
  },
  {
    code: "cells.read",
    name: "Leer células",
    description: "Ver células dentro del scope autorizado.",
  },
  {
    code: "cells.create",
    name: "Crear células",
    description: "Abrir nuevas células dentro del Ministerio autorizado.",
  },
  {
    code: "cells.update",
    name: "Actualizar células",
    description: "Editar horarios, estado y datos de células.",
  },
  {
    code: "cells.manage_members",
    name: "Gestionar miembros de célula",
    description: "Agregar, retirar y reasignar membresías.",
  },
  {
    code: "cells.attendance",
    name: "Registrar asistencia de célula",
    description: "Crear sesiones y marcar asistencia semanal.",
  },
  {
    code: "leaders.read",
    name: "Leer liderazgo",
    description: "Ver estados de liderazgo y progreso G12 en el alcance.",
  },
  {
    code: "leaders.mark_eligible",
    name: "Marcar apto para liderar",
    description: "Registrar elegibilidad/unción pastoral.",
  },
  {
    code: "leaders.activate",
    name: "Activar líderes",
    description: "Activar líderes y abrir su célula.",
  },
  {
    code: "leaders.deactivate",
    name: "Desactivar líderes",
    description: "Desactivar líderes con control de estructura.",
  },
  {
    code: "leaders.manage_tree",
    name: "Gestionar árbol",
    description: "Administrar relaciones generacionales.",
  },
  {
    code: "leaders.view_descendants",
    name: "Ver descendientes",
    description: "Navegar el subárbol pastoral autorizado.",
  },
  {
    code: "g12.convert_twelve",
    name: "Convertir a Célula de 12",
    description: "Convertir célula evangelística con 12 líderes activos.",
  },
  {
    code: "audit.read",
    name: "Leer auditoría",
    description: "Consultar audit logs autorizados.",
  },
  {
    code: "process.read",
    name: "Leer Escalera del Éxito",
    description: "Ver progreso pastoral (Consolidar / UDV) en el alcance.",
  },
  {
    code: "process.update",
    name: "Actualizar proceso pastoral",
    description: "Iniciar/pausar/retomar etapas de la Escalera.",
  },
  {
    code: "consolidation.manage",
    name: "Gestionar Consolidar",
    description: "Completar y administrar Consolidar.",
  },
  {
    code: "udv.read",
    name: "Leer Universidad de la Vida",
    description: "Ver ciclos, inscritos y progreso UDV.",
  },
  {
    code: "udv.manage",
    name: "Gestionar Universidad de la Vida",
    description: "Inscribir, pausar y completar participantes UDV.",
  },
  {
    code: "udv.attendance",
    name: "Asistencia UDV",
    description: "Registrar asistencia y recuperaciones autorizadas.",
  },
  {
    code: "school.cycles.manage",
    name: "Gestionar ciclos formativos",
    description: "Crear/activar/cerrar ciclos de programas.",
  },
  {
    code: "school.catalog.manage",
    name: "Gestionar catálogo formativo",
    description: "Administrar programas y módulos configurables.",
  },
  {
    code: "destination.read",
    name: "Leer Capacitación Destino",
    description: "Ver niveles, ciclos y progreso Destino en el alcance.",
  },
  {
    code: "destination.manage",
    name: "Gestionar Capacitación Destino",
    description: "Inscribir y administrar participantes Destino.",
  },
  {
    code: "destination.attendance",
    name: "Asistencia Destino",
    description: "Registrar asistencia Destino (ciclos asignados o alcance).",
  },
  {
    code: "destination.complete_academic",
    name: "Completar académico Destino",
    description: "Marcar componente académico de un nivel Destino.",
  },
  {
    code: "destination.complete_level",
    name: "Completar nivel Destino",
    description: "Aprobar formalmente un nivel Destino.",
  },
  {
    code: "destination.override_requirement",
    name: "Override requisito Destino",
    description: "Excepción auditada de requisitos pastorales/académicos.",
  },
  {
    code: "training.cycles.assign_staff",
    name: "Asignar staff de ciclo",
    description: "Definir profesores/responsables de ciclos formativos.",
  },
  {
    code: "ministerial_school.read",
    name: "Leer Escuela Ministerial",
    description: "Ver ciclos y progreso de Escuela Ministerial.",
  },
  {
    code: "ministerial_school.manage",
    name: "Gestionar Escuela Ministerial",
    description: "Inscribir y administrar participantes EM.",
  },
  {
    code: "ministerial_school.attendance",
    name: "Asistencia Escuela Ministerial",
    description: "Registrar asistencia EM.",
  },
  {
    code: "ministerial_school.complete",
    name: "Completar Escuela Ministerial",
    description: "Marcar académico y completar formalmente EM.",
  },
  {
    code: "reencounter.read",
    name: "Leer Re-Encuentro",
    description: "Ver eventos y progreso de Re-Encuentro.",
  },
  {
    code: "reencounter.manage",
    name: "Gestionar Re-Encuentro",
    description: "Inscribir participantes en Re-Encuentro.",
  },
  {
    code: "reencounter.attendance",
    name: "Asistencia Re-Encuentro",
    description: "Registrar asistencia al evento Re-Encuentro.",
  },
  {
    code: "reencounter.complete",
    name: "Completar Re-Encuentro",
    description: "Completar formalmente Re-Encuentro.",
  },
  {
    code: "send.read",
    name: "Leer Enviar",
    description: "Ver aptos y progreso de Enviar.",
  },
  {
    code: "send.manage",
    name: "Gestionar Enviar",
    description: "Iniciar y administrar proceso Enviar.",
  },
  {
    code: "send.complete",
    name: "Completar Enviar",
    description: "Marcar Enviar completado (no activa liderazgo).",
  },
  {
    code: "transfers.read",
    name: "Leer transferencias",
    description: "Ver solicitudes pastorales de transferencia.",
  },
  {
    code: "transfers.request",
    name: "Solicitar transferencias",
    description: "Crear solicitudes de transferencia pastoral.",
  },
  {
    code: "transfers.approve",
    name: "Aprobar transferencias",
    description: "Aprobar o rechazar transferencias pastorales.",
  },
  {
    code: "transfers.execute",
    name: "Ejecutar transferencias",
    description: "Ejecutar transferencias aprobadas de forma atómica.",
  },
  {
    code: "organization.transfer_network",
    name: "Transferir Red",
    description: "Cambiar Red organizacional de una persona.",
  },
  {
    code: "organization.transfer_ministry",
    name: "Transferir Ministerio",
    description: "Cambiar Ministerio General de una persona.",
  },
  {
    code: "leadership.reassign",
    name: "Reasignar liderazgo",
    description: "Reasignar líder directo y estructuras.",
  },
  {
    code: "leadership.move_subtree",
    name: "Mover subárbol",
    description: "Mover líder con descendientes y reconstruir closure.",
  },
  {
    code: "leadership.deactivate_with_structure",
    name: "Desactivar con estructura",
    description: "Desactivar líder resolviendo plan de reasignación.",
  },
  {
    code: "cells.reassign_structure",
    name: "Reasignar estructura de células",
    description: "Resolver células y membresías en transferencias.",
  },
] as const;

const CELL_PERMS = [
  "cells.read",
  "cells.create",
  "cells.update",
  "cells.manage_members",
  "cells.attendance",
] as const;

const LEADER_PERMS = [
  "leaders.read",
  "leaders.mark_eligible",
  "leaders.activate",
  "leaders.deactivate",
  "leaders.manage_tree",
  "leaders.view_descendants",
  "g12.convert_twelve",
] as const;

const PROCESS_PERMS = [
  "process.read",
  "process.update",
  "consolidation.manage",
  "udv.read",
  "udv.manage",
  "udv.attendance",
  "school.cycles.manage",
  "destination.read",
  "destination.manage",
  "destination.attendance",
  "destination.complete_academic",
  "destination.complete_level",
  "training.cycles.assign_staff",
  "ministerial_school.read",
  "ministerial_school.manage",
  "ministerial_school.attendance",
  "ministerial_school.complete",
  "reencounter.read",
  "reencounter.manage",
  "reencounter.attendance",
  "reencounter.complete",
  "send.read",
  "send.manage",
  "send.complete",
] as const;

const TRANSFER_PERMS = [
  "transfers.read",
  "transfers.request",
  "transfers.approve",
  "transfers.execute",
  "organization.transfer_network",
  "organization.transfer_ministry",
  "leadership.reassign",
  "leadership.move_subtree",
  "leadership.deactivate_with_structure",
  "cells.reassign_structure",
] as const;

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  superadmin: [
    "platform.configure",
    "ministry.manage",
    "ministry.read",
    "network.read",
    "users.read",
    "users.assign_roles",
    "persons.read",
    "persons.write",
    ...CELL_PERMS,
    ...LEADER_PERMS,
    ...PROCESS_PERMS,
    ...TRANSFER_PERMS,
    "school.catalog.manage",
    "destination.override_requirement",
    "audit.read",
  ],
  leader_general: [
    "ministry.read",
    "network.read",
    "users.read",
    "persons.read",
    "persons.write",
    ...CELL_PERMS,
    ...LEADER_PERMS,
    ...PROCESS_PERMS,
    ...TRANSFER_PERMS,
    "destination.override_requirement",
    "audit.read",
  ],
  leader: [
    "persons.read",
    "persons.write",
    "network.read",
    "cells.read",
    "cells.update",
    "cells.manage_members",
    "cells.attendance",
    "leaders.read",
    "leaders.mark_eligible",
    "leaders.activate",
    "leaders.view_descendants",
    "g12.convert_twelve",
    "process.read",
    "process.update",
    "consolidation.manage",
    "udv.read",
    "udv.manage",
    "udv.attendance",
    "destination.read",
    "destination.manage",
    "destination.attendance",
    "destination.complete_academic",
    "destination.complete_level",
    "ministerial_school.read",
    "ministerial_school.manage",
    "ministerial_school.attendance",
    "ministerial_school.complete",
    "reencounter.read",
    "reencounter.manage",
    "reencounter.attendance",
    "reencounter.complete",
    "send.read",
    "send.manage",
    "send.complete",
    "transfers.read",
    "transfers.request",
    "organization.transfer_network",
    "leadership.reassign",
    "cells.reassign_structure",
  ],
  staff: [
    "persons.read",
    "persons.write",
    "network.read",
    "ministry.read",
    "cells.read",
    "cells.attendance",
    "leaders.read",
    "process.read",
    "udv.read",
    "udv.attendance",
    "destination.read",
    "destination.attendance",
    "ministerial_school.read",
    "ministerial_school.attendance",
    "reencounter.read",
    "reencounter.attendance",
  ],
};
